before_all do
    ensure_git_branch
    ensure_git_status_clean
    git_pull
end

platform :ios do
    private_lane :update_version do
        app__store_version = get_app_store_version_number(bundle_id: 'ReactNativeFastlane.xcodeproj')
        plist_version = get_version_number_from_plist(xcodeproj: './ios/ReactNativeFastlane.xcodeproj')
        if Gem::Version.new(plist_version.to_f) == Gem::Version.new(app_store_version.to_f)
            UI.message "Bumping minor"
            increment_version_number_in_plist(xcodeproj: './ios/ReactNativeFastlane.xcodeproj', bump_type: 'minor')
        else
            UI.message "Bumping patch"
            increment_version_number_in_plist(xcodeproj: './ios/ReactNativeFastlane.xcodeproj', bump_type: 'patch')
        end
    end
    private_lane :staging_build do
        increment_build_number_in_plist(xcodeproj: './ios/fastlaneTest.xcodeproj', target:  'ReactNativeFastlane')
        gym(scheme: 'fastlaneTest', workspace: './ios/fastlaneTest.xcworkspace')
    end

    lane :beta do
        staging_build
        upload_to_testflight(username: "workmateuszrybin@gmail.com", app_identifier: 'org.reactjs.native.example.fastlaneTest')
        commit_version_bump(message: 'bump build')
        push_to_git_remote
    end
end


