name: Master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: 12
      - run: |
          yarn install --network-timeout 1000000
          yarn lint
        name: Build and Test
      - name: "Trigger next workflow"
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPATCH_API_PAT }}
          event-type: docker-build
          client-payload: '{"ref": "${{ github.ref }}", "tag": "latest"}'

      # - name: Push to next branch
      #   uses: actions-x/commit@v2
      #   with:
      #     branch: next