name: Commits pushed to master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build and Test
        run: |
          export APPCENTER_ACCESS_TOKEN=dc1743315f0c7b5cae0fc58fa8e7cf2456ee0d18
          yarn install --frozen-lockfile --network-timeout 1000000
          # yarn lint
          npm install -g appcenter-cli
          INPUT=$(appcenter build queue -b master --app "MattRybin/TestApp-1" --output json | jq ".buildId")
          chmod +x scripts/wait-on-app-center-build.sh
          ./scripts/wait-on-app-center-build.sh $INPUT

  trigger_next_branch:
    runs-on: ubuntu-latest
    name: Trigger Next Branch
    needs: build
    steps:
      - name: Trigger next branch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Merge master into next branch
          token: ${{ secrets.PERSONAL_TOKEN }}