name: 'Next Merge'

on:
  repository_dispatch:
    types: [docker-build]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'next'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'