name: 'Merge master into next branch'

on: workflow_dispatch

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    name: Merge master branch
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'next'
          commit_message_template: '[CI] Merged {source_ref} into target {target_branch}'
