name: Commits pushed to next branch

on:
  push:
    branches: [next]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build and Test
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          export APPCENTER_ACCESS_TOKEN=dc1743315f0c7b5cae0fc58fa8e7cf2456ee0d18
          yarn install --frozen-lockfile --network-timeout 1000000
          # yarn lint
          npm install -g appcenter-cli
          INPUT=$(appcenter build queue -b next --app "MattRybin/TestApp-1" --output json | jq ".buildId")
          chmod +x scripts/wait-on-app-center-build-next.sh
          ./scripts/wait-on-app-center-build-next.sh $INPUT